### ISSUE TITLE
Cluster get-credentials behaviour changed: kubeconfig is not containing auth information

### ISSUE THREAD

**Issue by simonswine** [kelseyhightower/kubernetes-cluster-federation#14]
Hey!

I have just figured out, that get-credentials is not returning client certificates anymore. So the step were we generate the kubeconfig files per cluster is not containing any auth infromation:

```
gcloud --version
Google Cloud SDK 124.0.0
alpha 2016.08.29
beta 2016.08.29
bq 2.0.24
bq-nix 2.0.24
core 2016.08.29
core-nix 2016.08.29
gcloud 
gsutil 4.21
gsutil-nix 4.21
```

```
kubectl config view --flatten --minify               
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XX
    server: https://104.199.X.Y
  name: gke_simonswine-demo_asia-east1-b_fed-asia-east
contexts:
- context:
    cluster: gke_simonswine-demo_asia-east1-b_fed-asia-east
    user: gke_simonswine-demo_asia-east1-b_fed-asia-east
  name: gke_simonswine-demo_asia-east1-b_fed-asia-east
current-context: gke_simonswine-demo_asia-east1-b_fed-asia-east
kind: Config
preferences: {}
users:
- name: gke_simonswine-demo_asia-east1-b_fed-asia-east
  user:
    auth-provider:
      config: null
      name: gcp
```

I suggest to get auth info from describe like that:

```
DATA=$(gcloud  --format json container clusters describe <name> --zone <zone>)
MASTER_URL="https://$(echo "${DATA}" | jq -r ".endpoint")"
MASTER_CA_CERT=$(echo "${DATA}" | jq -r ".masterAuth.clusterCaCertificate")
CLIENT_CERT=$(echo "${DATA}" | jq -r ".masterAuth.clientCertificate")
CLIENT_KEY=$(echo "${DATA}" | jq -r ".masterAuth.clientKey")
```
