### ISSUE TITLE
Federated NGINX Service - type: NodePort

### ISSUE THREAD

**Issue by jamesbuckett** [kelseyhightower/kubernetes-cluster-federation#43]
The file `kubernetes-cluster-federation/services/nginx.yaml`
has 
	`type: NodePort`
Should be
	`type: LoadBalancer`

File should read : 

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: nginx
  type: LoadBalancer
```
